apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filestore
  namespace: hiddenite
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: replicated-storage
  resources:
    requests:
      storage: 200Gi
