accessLog:
  enabled: true
  # Limit the access log to only those requests which are concerning for security
  filters:
    statusCodes: "400,401,403,405,406,407,411,412,413,414,415,416,421,422,423,424,425,426,428,429,431,451,500,501,502,503,504,505,506,507,508,510,511"

ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.bamilab.space`)
    entryPoints:
      - web
      - websecure

metrics:
  prometheus:
    addRoutersLabels: true

ports:
  web:
    exposedPort: 80
  # Port 9100 is already taken by the node exporter on each node's system
  metrics:
    expose:
      default: true
    exposedPort: 9101

gateway:
  listeners:
    web:
      port: 80
      hostname: bamilab.space
      namespacePolicy:
        from: All

service:
  spec:
    type: LoadBalancer
    externalIPs:
      - 172.0.0.10
      - 172.0.0.11
      - 172.0.0.12
