apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filestore
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: replicated-storage
  resources:
    requests:
      storage: 10Gi
