apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud-db
  namespace: default
spec:
  instances: 2

  imageName: ghcr.io/cloudnative-pg/postgresql:17

  backup:
    volumeSnapshot:
      className: zfs-local-snapshot-class
      snapshotOwnerReference: backup

  bootstrap:
    initdb:
      database: nextcloud
      owner: nextcloud

  storage:
    size: 10Gi
    storageClass: zfs-local-dataset

---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: nextcloud-db-backup
spec:
  cluster:
    name: nextcloud-db
  method: volumeSnapshot
  schedule: '0 0 0 * * *'
  backupOwnerReference: cluster
  immediate: true
