apiVersion: v1
kind: Pod
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  volumes:
    - name: nas-mount
      hostPath:
        path: /mnt/nas/nextcloud
        type: Directory
  containers:
    - name: app
      image: docker.io/library/nextcloud:latest
      imagePullPolicy: Never
      volumeMounts:
        - name: nas-mount
          mountPath: /mnt
      env:
        - name: POSTGRES_DB
          value: "nextcloud"
        - name: POSTGRES_USER
          value: "nextcloud"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-db-app
              key: password
        - name: NEXTCLOUD_SECRET
          valueFrom:
            secretKeyRef:
              name: nextcloud
              key: secret
        - name: PASSWORD_SALT
          valueFrom:
            secretKeyRef:
              name: nextcloud
              key: password-salt
