apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-site
  namespace: stonenet
  labels:
    app: production-site
spec:
  selector:
    matchLabels:
      app: production-site
  template:
    metadata:
      labels:
        app: production-site
    spec:
      volumes:
        - name: nas-mount
          nfs:
            server: nas.kubes
            path: /exhdd/stonenet-site
            readOnly: true
      containers:
        - name: app
          image: docker.io/library/stonenet-site:latest
          imagePullPolicy: Never
          volumeMounts:
            - name: nas-mount
              mountPath: /mnt
