apiVersion: v1
kind: Pod
metadata:
  name: site-production
  namespace: stonenet
  labels:
    app: site-production
spec:
  containers:
    - name: app
      image: docker.io/library/stonenet-site:latest
      imagePullPolicy: Never
