apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: get-stonenet-pvc
  namespace: stonenet
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: replicated-storage
  resources:
    requests:
      storage: 10Gi
