apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: release-files
  namespace: stonenet
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: replicated-storage
  resources:
    requests:
      storage: 10Gi
