apiVersion: apps/v1
kind: Deployment
metadata:
  name: production
  namespace: owncast
  labels:
    app: production
spec:
  selector:
    matchLabels:
      app: production
  template:
    metadata:
      labels:
        app: production
    spec:
      volumes:
        - name: nas-mount
          nfs:
            server: nas.kubes
            path: /exhdd/owncast
            readOnly: false
      containers:
        - name: app
          image: docker.io/library/owncast:latest
          imagePullPolicy: Never
          env:
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: admin-password
