apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: owncast
spec:
  type: NodePort
  
  selector:
    app: production
    
  ports:
  - name: http
    port: 6962 # OWNC
    targetPort: 8080
    nodePort: 30003
    protocol: TCP
