apiVersion: apps/v1
kind: Deployment
metadata:
  name: main
  namespace: grafana
  labels:
    app: main
spec:
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
        - name: app
          image: docker.io/library/grafana:latest
          imagePullPolicy: Never
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-app
                  key: password
