apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database
  namespace: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: replicated-storage
  resources:
    requests:
      storage: 10Gi
